cursor            #ffb59b
cursor_text_color #55200a

foreground            #f1dfd9
background            #140c0a
selection_foreground  #442a21
selection_background  #e7bdb0
url_color             #e7bdb0

#: black 000000 767676
color0  #1a110f
color8  #3d322f
#: red cc0403 f2201f
color1 #ffb59b
color9 #72351e

#: green 19cb00 23fd00
color2  #e7bdb0
color10 #ffdbcf
#: yellow cecb00 fffd00
color3  #d5c68e
color11 #f2e2a7
#: blue 0d73cc 1a8fff
color4  #72351e
color12 #ffb59b
#: magenta cb1ed1 fd28ff
color5  #5d4036
color13 #e7bdb0
#: cyan 0dcdcd 14ffff
color6  #50461a
color14 #d5c68e
#: white dddddd ffffff
color7  #d8c2bb
color15 #f1dfd9

mark1_foreground #380d00
mark1_background #ffdbcf
mark2_foreground #2c160d
mark2_background #ffdbcf
mark3_foreground #221b00
mark3_background #f2e2a7

active_tab_foreground #55200a
active_tab_background #ffb59b
inactive_tab_foreground #ffdbcf
inactive_tab_background #72351e

active_border_color #ffb59b
inactive_border_color #55200a
# bell_border_color #ff5a00