cursor            #e7c26c
cursor_text_color #3f2e00

foreground            #ebe1d4
background            #110e07
selection_foreground  #3a2f15
selection_background  #d7c4a0
url_color             #d7c4a0

#: black 000000 767676
color0  #17130b
color8  #39342b
#: red cc0403 f2201f
color1 #e7c26c
color9 #5a4300

#: green 19cb00 23fd00
color2  #d7c4a0
color10 #f4e0bb
#: yellow cecb00 fffd00
color3  #afcfab
color11 #cbebc6
#: blue 0d73cc 1a8fff
color4  #5a4300
color12 #e7c26c
#: magenta cb1ed1 fd28ff
color5  #52452a
color13 #d7c4a0
#: cyan 0dcdcd 14ffff
color6  #324d31
color14 #afcfab
#: white dddddd ffffff
color7  #d0c5b4
color15 #ebe1d4

mark1_foreground #251a00
mark1_background #ffdf9a
mark2_foreground #241a04
mark2_background #f4e0bb
mark3_foreground #062109
mark3_background #cbebc6

active_tab_foreground #3f2e00
active_tab_background #e7c26c
inactive_tab_foreground #ffdf9a
inactive_tab_background #5a4300

active_border_color #e7c26c
inactive_border_color #3f2e00
# bell_border_color #ff5a00