cursor            #85d2e7
cursor_text_color #003641

foreground            #dee3e6
background            #090f11
selection_foreground  #1d343a
selection_background  #b2cbd3
url_color             #b2cbd3

#: black 000000 767676
color0  #0f1416
color8  #303638
#: red cc0403 f2201f
color1 #85d2e7
color9 #004e5d

#: green 19cb00 23fd00
color2  #b2cbd3
color10 #cee7ef
#: yellow cecb00 fffd00
color3  #bfc4eb
color11 #dee1ff
#: blue 0d73cc 1a8fff
color4  #004e5d
color12 #85d2e7
#: magenta cb1ed1 fd28ff
color5  #344a51
color13 #b2cbd3
#: cyan 0dcdcd 14ffff
color6  #3f4565
color14 #bfc4eb
#: white dddddd ffffff
color7  #bfc8cb
color15 #dee3e6

mark1_foreground #001f26
mark1_background #adecff
mark2_foreground #061f25
mark2_background #cee7ef
mark3_foreground #131937
mark3_background #dee1ff

active_tab_foreground #003641
active_tab_background #85d2e7
inactive_tab_foreground #adecff
inactive_tab_background #004e5d

active_border_color #85d2e7
inactive_border_color #003641
# bell_border_color #ff5a00