cursor            #dcb9f8
cursor_text_color #3f2358

foreground            #e8e0e8
background            #100d12
selection_foreground  #372c3f
selection_background  #d1c1d9
url_color             #d1c1d9

#: black 000000 767676
color0  #151217
color8  #373339
#: red cc0403 f2201f
color1 #dcb9f8
color9 #573a70

#: green 19cb00 23fd00
color2  #d1c1d9
color10 #edddf6
#: yellow cecb00 fffd00
color3  #f3b7bc
color11 #ffd9dc
#: blue 0d73cc 1a8fff
color4  #573a70
color12 #dcb9f8
#: magenta cb1ed1 fd28ff
color5  #4e4256
color13 #d1c1d9
#: cyan 0dcdcd 14ffff
color6  #663a3f
color14 #f3b7bc
#: white dddddd ffffff
color7  #cdc4ce
color15 #e8e0e8

mark1_foreground #290c41
mark1_background #f1dbff
mark2_foreground #211829
mark2_background #edddf6
mark3_foreground #321016
mark3_background #ffd9dc

active_tab_foreground #3f2358
active_tab_background #dcb9f8
inactive_tab_foreground #f1dbff
inactive_tab_background #573a70

active_border_color #dcb9f8
inactive_border_color #3f2358
# bell_border_color #ff5a00