#enlace simbolico al tema
include ./themes/matugen.conf


#transparencia
background_opacity 0.85

#Margenes de multiples consolas
window_margin_width 10

#background pang
background_image_layout scaled
background_tint 0.90
background_tint_gaps -10


# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME