preload = /home/david/Imágenes/wallpaperMh.jpg
wallpaper {
monitor = eDP-1
path = /home/david/Imágenes/wallpaperMh.jpg
fit_mode = cover
}
wallpaper {
monitor = HDMI-A-1
path = /home/david/Imágenes/wallpaperMh.jpg
fit_mode = cover
}
