# : Manager [[[

[mgr]
cwd = { fg = "#f0dfd6" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#c8cf61", bg = "#c8cf61" }
marker_cut      = { fg = "#e3e7af", bg = "#e3e7af" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#c7ca95", bg = "#c7ca95" }

# Count
count_copied   = { fg = "#1b1d00", bg = "#e3e7af" }
count_cut      = { fg = "#1b1d00", bg = "#e3e7af" }
count_selected = { fg = "#4e2600", bg = "#c7ca95" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb781" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#ffb781", bold = true, bg = "#19120d" }
inactive  = { fg = "#e4bfa7", bg = "#19120d" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#ffb781", fg = "#4e2600", bold = true }
normal_alt  = { bg = "#52443b", fg = "#d6c3b7" }

# Select mode
select_main = { bg = "#e4bfa7", fg = "#422b1a", bold = true }
select_alt  = { bg = "#52443b", fg = "#d6c3b7" }

# Unset mode
unset_main = { bg = "#c7ca95", fg = "#2f330c", bold = true }
unset_alt  = { bg = "#52443b", fg = "#d6c3b7" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#b96b39" }
perm_write = { fg = "#808442" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#b9c33a" }
perm_sep   = { fg = "#ff812b" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#ffb781", bg = "#413731" }
progress_error  = { fg = "#ffb4ab", bg = "#413731" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#413731" }
cand = { fg = "#ffb781" }
rest = { fg = "#4e2600" }
desc = { fg = "#f0dfd6" }
separator = " ▶ "
separator_style = { fg = "#f0dfd6" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#c7ca95" }
title_warn  = { fg = "#ffb781" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#ffb781" }
active = { fg = "#c7ca95", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb781" }
value  = { fg = "#f0dfd6" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#ffb781", bg = "#4e2600" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#ffb781" }
title   = {}
hovered = { fg = "#e3e7af", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#f0dfd6" }
run    = { fg = "#f0dfd6" }
footer = { fg = "#422b1a", bg = "#e4bfa7" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#f0dfd6" },
    { url = "*/", fg = "#ffb781" },
]

# : ]]]
