# : Manager [[[

[mgr]
cwd = { fg = "#e8e0e8" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#ff737e", bg = "#ff737e" }
marker_cut      = { fg = "#ffd9dc", bg = "#ffd9dc" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#f3b7bc", bg = "#f3b7bc" }

# Count
count_copied   = { fg = "#321016", bg = "#ffd9dc" }
count_cut      = { fg = "#321016", bg = "#ffd9dc" }
count_selected = { fg = "#3f2358", bg = "#f3b7bc" }

# Border
border_symbol = "│"
border_style  = { fg = "#dcb9f8" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#dcb9f8", bold = true, bg = "#151217" }
inactive  = { fg = "#d1c1d9", bg = "#151217" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#dcb9f8", fg = "#3f2358", bold = true }
normal_alt  = { bg = "#4b454d", fg = "#cdc4ce" }

# Select mode
select_main = { bg = "#d1c1d9", fg = "#372c3f", bold = true }
select_alt  = { bg = "#4b454d", fg = "#cdc4ce" }

# Unset mode
unset_main = { bg = "#f3b7bc", fg = "#4b252a", bold = true }
unset_alt  = { bg = "#4b454d", fg = "#cdc4ce" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#8b629f" }
perm_write = { fg = "#dd3442" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#ff404f" }
perm_sep   = { fg = "#b642ff" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#dcb9f8", bg = "#3c383e" }
progress_error  = { fg = "#ffb4ab", bg = "#3c383e" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3c383e" }
cand = { fg = "#dcb9f8" }
rest = { fg = "#3f2358" }
desc = { fg = "#e8e0e8" }
separator = " ▶ "
separator_style = { fg = "#e8e0e8" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#f3b7bc" }
title_warn  = { fg = "#dcb9f8" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#dcb9f8" }
active = { fg = "#f3b7bc", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#dcb9f8" }
value  = { fg = "#e8e0e8" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#dcb9f8", bg = "#3f2358" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#dcb9f8" }
title   = {}
hovered = { fg = "#ffd9dc", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e8e0e8" }
run    = { fg = "#e8e0e8" }
footer = { fg = "#372c3f", bg = "#d1c1d9" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e8e0e8" },
    { url = "*/", fg = "#dcb9f8" },
]

# : ]]]
